### PR TITLE
Porting solr text tagger to Lucene/Solr 5.x.

### PR DESCRIPTION
**Pull request by jdeolive**
This updates the module to the soon to be released solr 5.0. I built it against the lucene_solr_5_0_0 tag in the solr svn repo. Unit tests pass and smoke testing in a running solr 5.x instance works well. 

I am not sure what the strategy for tracking upstream solr versions in this repo is, whether this should be on master or perhaps another branch.  If it is preferred for this to go into a branch I'm happy to rework as necessary.

### CODE REVIEW

**Comment by dsmiley** [comment]
Hi Justin,
I'm willing for this to go to master branch right now... a comment in pom.xml to let people know about support for Solr 4 in the tagger version 2.0 and prior would be good.  5.0 isn't out on Maven yet so I won't merge; Travis CI complains.

**Comment by jdeolive** [comment]
Great, thanks David. I'll update the pom with a comment as you suggest, and will ping back once all of the maven artifacts are in place. Speaking of Travis, I guess we'll also need to update the build matrix accordingly and strip out the builds against solr 4.x?

**Comment by jdeolive** [comment]
Update on this one, I just updated the pom to add the comment, and updated the travis build config. Travis seems happy now.

**Comment by dsmiley** [comment]
Thanks Justin.

**Pull request merged**
